# Setup
title:               Midwest Algebra Conspiracy
tagline:             a Graduate Student Blog
description:         >- # this means to ignore newlines until "url:"
  A group blog by a few graduate students studying algebra across the midwest.
url:                 https://midwest-algebra-conspiracy.github.io
baseurl:             '' # the subpath of your site, e.g. /blog
gtag:                UA-140716120-1 # Google Analytics Tag

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for entries
collections:
  texts:
    output: true
  examples:
    output: true
  authors:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  footnote_backlink: "&#x21a9;&#xfe0e;"
  enable_coderay: false
#  math_engine: null # pending https://github.com/github/pages-gem/pull/545

# Exclusions from the final site
exclude:
  - vendor
  - README.md
  - LICENSE.md
  - Gemfile*
  - proof.gemspec

# Theme
remote_theme: "mahrud/proof"
